exclude: docs/
repos:
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: flake8
        language: system
        types: [python]
      - id: black
        name: Black
        entry: black
        language: system
        types: [python]
