jobs:
  - job: Template_Checker
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo "$(Build.SourceBranchName)"
        echo $(Build.SourceBranchName)
        make -C azure-pipelines check-required-files
      displayName: 'Checking for requirements files'