jobs:
  - job: Deployer
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: installing_python.yml
    - script: |
        make -C azure-pipelines install-base
      displayName: 'Installing Requirements'
    - bash: |
        (cd .. && mkdir -p ./conf/local)
        (cd .. && echo "azure:
          deploy:
            compute: $(PRODUCTION_COMPUTE)
            resource_group: $(PRODUCTION_RESOURCE_GROUP)
            workspace: $(PRODUCTION_WORKSPACE)
        " >> ./conf/local/credentials.yml)
      displayName: Get deployment configuration
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'svc-datascience-prd'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          pipes=($(KEDRO_PIPELINES))
          for pipe in "${pipes[@]}"
          do
            kedro azure pipeline create --pipeline $pipe --branch $(Build.SourceBranchName)
            kedro azure pipeline publish --pipeline $pipe --branch $(Build.SourceBranchName)
          done
      displayName: Deploy to production